### ISSUE TITLE
fix relative links from wordpress

### ISSUE THREAD

**Issue by grahamlopez** [olcf/olcf-user-docs#10]
## todo
Here are is a preliminary list of offenders found with a simple grep `grep -r '</for-users/' *`, but there are other forms of brokenness as well:
- [x] getting_started/index.rst
- [x] olcf_policy_guide.rst
- [x] documents_and_forms.rst
- [x] getting_started.rst
- [x] frequently_asked_questions.rst
- [x] summit_user_guide.rst (to be done during re-sync)
- [x] rhea_user_guide.rst (to be done during re-sync)

## link types
For in-page relative links, something like this is broken:
```
`NVIDIA Volta V100 </for-users/system-user-guides/summit/nvidia-v100-gpus/>`__
```
while something like this is fine:
```
`hardware threads <#hardware-threads>`__
```
or the most robust way (should survive page restructuring and section renaming) for linking (espcially to other pages) within the documentation is to provide cross-references: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#ref-role

full URLs are okay:
```
`NVIDIA Volta Architecture White Paper <http://images.nvidia.com/content/volta-architecture/pdf/volta-architecture-whitepaper.pdf>`_
```

**Comment by grahamlopez** [comment]
This should be finished when #13 and #14 are resolved.

**Comment by grahamlopez** [comment]
The last sections are being merged soon. There are no more remaining known broken links. closing.
